schema_version: 1

context:
  name: google-genai
  version: "1.46.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/google_genai-${{ version }}.tar.gz
  sha256: 6824c31149fe3b1c7285b25f79b924c5f89fd52466f62e30f76954f8104fe3a7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
    - twine >=6.1.0
  run:
    - python >=${{ python_min }}
    - anyio >=4.8.0,<5.0.0
    - google-auth >=2.14.1,<3.0.0
    - httpx >=0.28.1,<1.0.0
    - pydantic >=2.0.0,<3.0.0
    - requests >=2.28.1,<3.0.0
    - tenacity >=8.2.3,<9.2.0
    - websockets >=13.0.0,<15.1.0
    - typing_extensions >=4.11.0,<5.0.0
tests:
  - python:
      imports:
        - google.genai
        - google.genai.types
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: GenAI Python SDK
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/python-genai

extra:
  recipe-maintainers:
    - hadim
