schema_version: 1

context:
  name: google-genai
  version: "1.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/google_genai-${{ version }}.tar.gz
  sha256: 7b365a767474becc899bb2f1a38bcdc4967f20645cbf9b7781bd38ad1a59c25b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - google-auth >=2.14.1,<3.0.0dev
    - pydantic >=2.0.0,<3.0.0dev
    - requests >=2.28.1,<3.0.0dev
    - websockets >=13.0,<15.0dev

tests:
  - python:
      imports:
        - google.genai
        - google.genai.types
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: GenAI Python SDK
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/python-genai

extra:
  recipe-maintainers:
    - hadim
